export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IkNhdmVpcmEiLCJlbWFpbCI6InJvcXVlQGVtYWlsLmNvbS5iciIsImlhdCI6MTY5Mzc2NTQ1OSwiZXhwIjoxNjk0MzcwMjU5LCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMSJ9.uRNyWY1l2tTCL1wLQcIOBIWP11G7XRQWgS2mn0Tn_nc';
